### ISSUE TITLE
Statistics: Style Page based on Design

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#113]
Approved Mockup: https://invis.io/9HRVDCMBJQC

## Description

Implement the page in CKAN portal. Design: https://invis.io/9HRVDCMBJQC

## Tasks

- [x] Implement the page mocked designs as HTML/CSS
- [x] Implement responsiveness
- [x] Review & Feedback
- [x] Implement Feedback (if any). 

## Acceptance Criteria

- [x] Statistics page is as per the mockup
- [x] All the features are working
- [x] Feedback items implemented
- [x] Tested on various devices for responsiveness and usability

**Comment by zelima** [comment]
FIXED
