### ISSUE TITLE
Fill Program Code according to Program Affiliation field and vice versa

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#120]
As an admin, I want package metadata fields, Program Code and Program Affiliation,  to be filed according to each other Eg: if type `015:00` in `Program Code` field than `Program Affiliation` would gate a valued of `bla bla`  (whatever corresponds to that code from schema), so that I don't have to memorize all of it

Grab the data from here https://project-open-data.cio.gov/data/FederalProgramInventory_FY13_MachineReadable_091613.csv

## Acceptance Criteria

- [ ] Field values are updated as defined above

## Tasks

- [ ] Update schema so that it has all the data
- [ ] Javascrip for filling field values automatically
