### ISSUE TITLE
About: Style Page based on Design

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#122]
Approved Mockup: https://invis.io/AVRZ389BW8K

## Description

Implement the page in CKAN portal. Design: https://invis.io/AVRZ389BW8K

## Tasks

- [x] Implement the page mocked designs as HTML/CSS
- [x] Implement responsiveness
- [x] Review & Feedback
- [x] Implement Feedback (if any). 

## Acceptance Criteria

- [x] About page is as per the mockup
- [x] All the features are working
- [x] Feedback items implemented
- [x] Tested on various devices for responsiveness and usability

**Comment by zelima** [comment]
@tanvirchahal anything remaining here?

**Comment by tanvirchahal** [comment]
@zelima all good

**Comment by zelima** [comment]
FIXED
