### ISSUE TITLE
Homepage: Style Page based on Design

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#124]
Approved Mockup: https://invis.io/E7RO1RWTKNF#/362649069_Home-V0-9-1a

## Description

Implement the page in CKAN portal. Design: https://invis.io/E7RO1RWTKNF#/362649069_Home-V0-9-1a

## Tasks

- [ ] Implement the page mocked designs as HTML/CSS
- [ ] Implement responsiveness
- [ ] Review & Feedback
- [ ] Implement Feedback (if any). 

## Acceptance Criteria

- [ ] Home page is as per the mockup
- [ ] All the features are working
- [ ] Feedback items implemented
- [ ] Tested on various devices for responsiveness and usability
