### ISSUE TITLE
CKAN; issue with how filtering is implemented at the ckan logic layer

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#128]
# Categories (renamed to Major Topic) logic need to emit a checkbox rather than a LI html

Github link https://github.com/CivicActions/ckanext-ed/issues/121

> High level user story: (already implemented). As a data stewart I want to be able to filter datasets by tags, publishers, level of data (spacial field) and major topics.

As a data stewart when filtering datasets on search page, I want to tick a checkbox instead of clicking and highlighting filter (current behaviour), because I just like that way.

## Acceptance Criteria

- [ ] I can see the checkbox(es) and able to tick and filter that way

## Tasks

- [x] Rename Categories to Topics
- [x] Locate template where categories items are returned
- [x] make sure FORM element is right, fix if needed/transfer to another template etc.
- [ ] Test

## Analysis

We have overridden the template responsible for displaying facets, so that it displays checkboxes instead of highlighting them. But whenever we are checking something (is also happening when highlighting) all the other filters disappear, except the ones that remaining datasets have 

Eg. If we have 2 dataset "XYZ" and "ABC" and the have following tags

- XYZ - cars
- ABC - animals, birds

Initially on dataset page would appear 2 datasets and 3 tags to filter with. If one would decide to filter the datasets by "animals" tag only dataset "ABC" would remain and 2 tags ("animals" and "birds") would remain, as the remaining dataset has only those tags. 

Expected behavior would be to filter datasets (1 detaset would remain) but number of tags would remains same (3).

## Solution

Currently search (dataset) page is displayed by X controller 
- [ ]
## QA

Links:
* CKAN original facet item function:
    * https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L981
* Sivan's WIP:
    * https://github.com/CivicActions/ckanext-ed/compare/categories-topics-checkboxes?expand=1#diff-81c0556466411b2b39046dc0d8770d2d
