### ISSUE TITLE
Sort choices for program field and make them searchable

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#135]
As a data stuart I want the list of choices for program field to be sorted, also want to type and filter, so that I can easily find though big list

## Acceptance Criteria

- [ ] Program field works as Licenses

## Tasks 

- [ ] Sort list and upload that way 
- [ ] Apply the license field's functionality to it
