### ISSUE TITLE
Add a new filter to dataset page, to filter by “Formats”, “Years” , “Geography”, “License”

### ISSUE THREAD

**Issue by sivang** [CivicActions/ckanext-ed#141]
As a data steward , I want to be able to filter the main page of datasets search results by the following fields:
- Formats (e.g CSV, TXT, JSON, XML)
- Years
- Geography (e.g. the location where this datasets applies to describes)
- License

Such that, it's easy for me to location datasets for my work , when I'm interested in certain years, places , formats of data and licenses to do my work.

## Tasks

- [ ] Find the existing logic, possibly from search facets , to do the filtering.
- [ ] Refactor , or create a new snippet for the dataset filter bar.
- [ ] Create the fields needed for the filtering if not already existing.
- [ ] Test

## Analysis

In CKAN we already have a way to filter data according to tags, publishers (offices, tags, categories etc) it would be wise to try to re use this logic instead of writing new one, but we may need to write new logic if that existing supports has some sorts of special affinity to the data attributes it already applies to (office, tages, categories etc).

**Comment by sivang** [comment]
After analysis it seems way to achieve this:
- [ ] Override and inherit form the `package` controller.
- [ ] Add another facet configuration as is already done in the controller for the left facets
- [ ] Use this facet from a new template created for the filter user interface.
