### ISSUE TITLE
Style Dataset Search Page based on mockups

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#143]
## Description
Implement the page in CKAN portal. Design: https://invis.io/YKRZ3IY35SW

## Tasks

- [x] Implement the page mocked designs as HTML/CSS
- [x] Implement responsiveness
- [x] Review & Feedback
- [x] Implement Feedback (if any). 

## Acceptance Criteria

- [x] Statistics page is as per the mockup
- [x] All the features are working
- [x] Feedback items implemented
- [x] Tested on various devices for responsiveness and usability
