### ISSUE TITLE
Display resource page on dataset page and make it change dynamically

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#163]
Implement per mockup https://projects.invisionapp.com/d/main#/console/17334086/365631557/preview

## Acceptance Criteria

- [x] "Selected" resource on dataset page
- [x] tables loading if available 
- [x] List on the left
- [x] able t select other resource

## Tasks

- [x] Update dataset controller to habdle "Select" (maybe use pin)
- [x] Mover stuff from resource templates end merge with dataset page
