### ISSUE TITLE
Pending requests dashboard page

### ISSUE THREAD

**Issue by amercader** [CivicActions/ckanext-ed#17]
## Overview

Admins need a way to have an overview of all the pending requests. A good place for this could be the user dashboard, as it is the first page users see when logging in.
We'll add a new tab that will display all datasets flagged with `approval_pending` on all the Offices that the user administers.

![screenshot_2018-12-05 manage - jane office admin - users - u s department of education](https://user-images.githubusercontent.com/200230/49508877-28485280-f884-11e8-9f7e-dfa8fe79265d.png)

## Tasks

- [x] Add a new tab to the dashboard page (extend [this](https://github.com/ckan/ckan/blob/master/ckan/templates/user/dashboard.html#L20))
- [x] Add a new `/dashboard/requests` endpoint + controller + template (check the `dashboard_datasets.html` one on CKAN core)
- [x] The controller should do a `pacakge_search` call that only include the pending datasets for the orgs the user belongs to (If the current setup doesn't support this we'll need to use `IPermissionLabels`)
- [x]  Show a list of datasets on the UI using the `package_list.html` snippet

Bonus points: Show number of requests in the tab title eg "My pending requests (12)"

**Comment by zelima** [comment]
FIXED
