### ISSUE TITLE
Change metadata that is displayed & add description above table

### ISSUE THREAD

**Issue by estebanruseler** [CivicActions/ckanext-ed#245]
**Description:** The aim to update the metadata section of the dataset with updated list. The first change is to have the description on top of the dataset information and then a number of new fields. Some of the metadata fields are dynamic (ie pulled from db) and some will be static html. 

Linked to [issue for moving this metadata table (and description) to a new tab called description in the dataset page](https://github.com/CivicActions/ckanext-ed/issues/246) 
Linked to [issue for updating the metadata in the add/edit dataset form](https://github.com/CivicActions/ckanext-ed/issues/256)

**Requirements for new metadata table**

Firstly, we want to add the description on top of the metadata table (called "Dataset Information"), this should 3 lines of text with the same font as the metadata table _with a show more show less if there is additional text_ @higorspinto I thought this after our conversation

| Metadata | Description | Notes | 
| -------- | -------- | -------- | 
| Created  | Dynamic  | No change | 
| Metadata last updated | Dynamic | No change | 
| Publisher | Dynamic | No change |
| Programs | Dynamic | Change to Program Code |
| Data level | Static | New, blank for now | 
| Organization | Static | New, blank for now | 
| License     | Dynamic | No change |
| Frequency | Static | New, blank for now |
| Helpdesk Phone Contact | Dynamic | No change | 
| Helpdesk Email Contact | Dynamic | No change | 
| Data Steward Name  | Dynamic | No change | 
| Data Steward Email | Dynamic | No change | 
| Access Level | Dynamic  |  No change  | 
| Spatial | Dynamic  |  No change  | 
| Data Representation Period - Start Date | Dynamic | No change |
| Data Representation Period - End Date | Dynamic | No change | 
| ~~References~~ | ~~Static~~ | No longer required |
| Unique identifier | Dynamic | CKAN id | 

Summary of change to the metadata table

* Description 
* Program changed to programe code
* Datalevel - dynamic
* Organization - static 
* Frequency - static 
* ~~References~~ - ~~static~~
* Unique Id - dynamic - CKAN id

## Acceptance criteria:
- [x] Metadata updated as per requirements
- [x] Created issue to update the add/edit dataset form
- [ ] ~~Unit test green~~ (see analysis)
  

## Task-list
- [x] Understand the codebase, where this code resides and any dependencies
- [x] For with docs template: In the documentation tab (where the dataset metadata currently is) add the Description metadata on top of the Dataset Information. This should be 3 lines of text the same font as the metadata table We know we store this (as it's shown in the dataset preview, we just don't display it. [Mock-up](https://datopian.invisionapp.com/freehand/mockup-Rp4DxOXSX?v=43d9uU7L%2B7Eu7mw9zUQlsQ%3D%3D&linkshare=urlcopied) of how it should look under docs metadata
  - [x] Update the frontend for to include a spot to enter this description field   
  - [x] Find the tag for description and insert in frontend code
  - [x] What is the max field length? Does it exceed 3 lines of text? If so we'll need a show more / show less solution. 
  - [x] Work out what to put if no description (prob leave blank and have more whitespace
  - [x] *Consider mobile view (as bootstrap it should work ok but worth double checking)* _Added
 since chat_
 - [x] The above steps are completed for both with and without docs templates (see analysis)
- [x] Update the table so that is as per requirements above
  - [x]    Add static html fields
  - [x]    For dynamic fields, first add the left hand column text. Then find the tag for the dynamic code, then tag it to the front-end
- [x] Update the "show more show less" code so that it shows the first 12 metadata fields
- [ ] ~~Create unit test (we might waive this step depending on time constraint, might just rely on UAT)~~  (see analysis)
- [x] UAT and/or unit test locally
- [x] Submit PR to Jovanka to review
- [x] Jovanka approves
- [x] Irakli to merge and deploy to https://us-ed-testing.ckan.io/
- [x] Higor tests if deployed as expected
- [x] Esteban does UAT

## Analysis

Two templates have to be updated, package and documentation. The templates are different to handle a dataset without documentation. When a dataset doesn't have documentation the package calls a template. The documentation template is called when the dataset has documentation.

### Show More/Less function

There are many ways to create a show more/less function with a long text. One approach can be done using only HTML code and taking advantage of Bootstrap classes. There is a class on bootstrap that implements a collapse behavior for a component, and this behavior can be controlled by a button or a link. We can do this function creating two divs, one for the show less (default) and the other for show more. Inside the divs we create a link to control the collapse behavior and assign two targets (both divs). When a user clicks on the show more/less link the current component is hidden and the other component is shown.

### Tests
 
Unit tests are not working and they need to be updated.

### Bugs

- Font size of the metadata banner. The link for the publisher is written with different font size from the rest of the banner. https://github.com/CivicActions/ckanext-ed/issues/250
  - Tested on old versions (1.2.4; 1.2.3; 1.2.2) and the bug appears on them.
- The markup shows up in the description on Show Less mode. https://github.com/CivicActions/ckanext-ed/issues/251

**Comment by estebanruseler** [comment]
Update: References is no longer required in the metadata table. Requirements updated.

**Comment by higorspinto** [comment]
@estebanruseler Ok.

**Comment by estebanruseler** [comment]
Jovanka's message to Esteban: "just a note, even if you don't have values for something at the moment, you can add the code for getting the values and they will show up when they are going to be added (guessing that you already have defined the fields and they are saved in the db). If you don't have values for a filed in the database, then the template is only going to show an empty filed, as it is at the moment in the PR. so you don't have to go and work on this task 2 times. This way the task is not finished."

To re-cap: we have requested the following new/changed metadata fields: 

- Description
- Program changed to programe code
- Data-level - dynamic
- Organization - static
- Frequency - static
- Unique Id - dynamic - CKAN id

Some of the fields we already have in the db but regarding the ones we don't, I just wanted to ship this asap. This change is a blocker to going live on the 28th with code freeze eop tomorrow and shipping #246 is really important (but not a go-live blocker) for the client. So I was looking for the quickest way to get these done. And then after deployment, we can improve it. 

So, thanks for your comment. Regarding your proposed solution of not leaving fields blank but creating the link to the backend now so when the data saves to the db it will display... 

Re Frequency - We have NOT defined the field and it is not saved in the db. 

Organization (=sub-org in CKAN) - if we can tie this to sub-org super easily then great, but I'm not even sure we fully finish developing this feature. I think we got 80% there and Ivan told us to stop. My hunch is the best is to leave blank especially as also this requirement might change following further discussion

**Comment by estebanruseler** [comment]
@higorspinto spotted a possible bug. The font size for publisher, show more for tags and Collections too big and should be in line in the other banner metadata field. Can you pls fix.
