### ISSUE TITLE
Create a new tab in dataset page called description

### ISSUE THREAD

**Issue by estebanruseler** [CivicActions/ckanext-ed#246]
**Description** Remove the dataset metadata from the docs tabs and move it to a new tab called description, as per the [mock-up](https://datopian.invisionapp.com/freehand/mockup-Rp4DxOXSX?v=43d9uU7L%2B7Eu7mw9zUQlsQ%3D%3D&linkshare=urlcopied)

[Linked to issue changing meta-data](https://github.com/CivicActions/ckanext-ed/issues/245)
[Linked to issue for updating the metadata in the add/edit dataset form](https://github.com/CivicActions/ckanext-ed/issues/256)

## Acceptance criteria: 

- [ ] Dataseta Metadata is displayed in a new tab called Description
- [ ] ~~UI testing is green~~ (see analysis)

## Task-list

- [x] Understand where the code base is (do that when you are doing issue 245) 
- [x] Create the new tab using the code of the Front-end code of the dataset (so that you inherit the links and manage button (non-technical hunch, see if this is indeed best approach)
- [x] Remove dataset metadata from docs tab
- [x] Add dataset metadata to the newly created description tab
- [x] Add the manage button to this page (this should same as on the dataset page) for users that are logged in
- [x] Ensure that when a user clicks on a dataset they are taken to the description page (this is worth thinking about and asking Jovanka how best to do this as the "home dataset" URL will need to change
- [x] Add the icon as mock-up (ask Tanvir if you get stuck here)
- [ ] ~~Create unit test (we might waive this step depending on time constraint, might just rely on UAT)~~ (see analysis)
- [x] UAT and/or unit test locally
- [x] Submit PR to Victor to review
- [x] Victor approves
- [ ] Victor to merge and deploy
- [ ] Higor tests if deployed as expected
- [ ] Esteban does UAT

## Analysis

We need to create a new route to display the dataset description and its metadata. 
```\dataset\description\<id>```

Some work needs to be done on the back-end to create the route and create a new action on the controller. Also, the landing page of the dataset should be the description page.

On the front-end, we need to create the tab, assign the correct icon, and create a new template to be rendered inside the new tab, as the requirements. Two templates have to be updated, dataset and documentation, with the correct parent id, to show the new tab.

### Changing Landing Page

When the user opens a dataset the package controller reads the template based on the package type. A CKAN core method (from CKAN Package Controller) is called to return the right template for the dataset. 

**Approach 1**

One approach to change the landing page is to override the method from CKAN core (_read_template). Copy the code from CKAN core and update it to return the template related to description. Also, a new action to call the resource page needs to be created on the controller.

**Approach 2**

Change the redirected URL to the description page.

### Testing

Tests are not running and they need to be updated.
