### ISSUE TITLE
Font size of the Dataset Metadata Banner 

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-ed#250]
The link for the publisher is written with a different font size from the rest of the banner. 

**Reproduce**

1. Open a dataset
2. Check the banner

![Dataset Metadat Banner font size bug](https://user-images.githubusercontent.com/20601698/73171787-5324e400-40e0-11ea-818f-b6fda39b3bab.png)

## Acceptance Criteria

- [ ] The banner is displayed correctly. All text with the same font size.

## Tasks

- [x] Analyse codebase
- [x] Understand CSS classes that rule the font sizes 
- [x] Define what is the best solution (What is the best font size for the banner - talk to the team)
- [x] Apply the solution
- [x] UAT locally
  - [x] Test in mobile view
- [x] Submit PR to Victor to review
- [x] Victor approves
- [x] Victor to merge and deploy
- [x] Higor UAT
- [ ] Esteban UAT
