### ISSUE TITLE
The markup shows up in the description on Show Less mode

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-ed#251]
The markup language shows up in the description on Show Less text mode. It happens only in some cases when the markup tag is not closed inside the number of characters that can be shown in less mode.

**Reproduce**

An example: https://us-ed-testing.ckan.io/dataset/docs/college-map

1. Create a dataset
2. Write a description with markdown and use markdown syntax right before the char number 330. The markdown should end after the char number 330.

![The markup language shows up in the description on Show Less mode](https://user-images.githubusercontent.com/20601698/73174547-c7628600-40e6-11ea-89c6-5ae94efea59f.png)

## Acceptance criteria

- [ ] The description is shown properly

## Tasks

- [x] Analyze when the bug happens
- [ ] Propose a solution and describe it in the Analysis section 
- [ ] Implement the solution
- [ ] UAT locally
   - [ ] Test in mobile view
- [ ] Submit PR to Jovanka to review
- [ ] Jovanka approves
- [ ] Irakli to merge

**Comment by higorspinto** [comment]
This issue was fixed on PR #254.
