### ISSUE TITLE
Collections with single quotes in their name break the facet filtering script

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-ed#259]
## Description

As a user, I have a collection that is called “Jason’s Collection”. I want to filter by it in the dataset search, so it would only show the datasets belonging to that collection.

What happens instead is that clicking on “Jason’s Collection” in the filters list has no effect.

Opening the browser console reveals that there’s an error in the script caused by the apostrophe (') in the collection name.

The task is to properly escape characters used as input when evaluating page scripts.

## Acceptance criteria:

- [ ] Clicking on any filter with single quotes in their name will work as expected
- [ ] Same goes for double quotes

## Tasks:

- [x] Understand the codebase, where this code resides and any dependencies
- [x] Write an analysis about how to approach
- [x] Define what is the best solution
- [x] Apply the solution
- [x] UAT locally
- [x] Submit PR to Victor to review
- [x] Victor approves
- [x] Victor to merge and deploy
- [x] Higor UAT
- [ ] Esteban UAT

## Analysis

The facet searching filtering is rendered by the ```search.html``` file.

A JS code inside the checkbox ``` onClick="javascript: item_ref = document.getElementById('Jason's Collection'); ``` breaks due to the apostrophe.

### Approach 1

Use the **name** of the collection instead of using the **title** (or **display name**) to identify HTML objects.

From: ```{% set item_id = "".join(item.display_name.split()) %}```

To: ```{% set item_id = "".join(item.name.split()) %}```

### Approach 2

Change the identifiers of the HTML objects to the **id's** of the collections.

From: ```{% set item_id = "".join(item.display_name.split()) %}```

To: ```{% set item_id = "".join(item.id) %}```

This includes some changes to the ```filter_collections``` helper function. Currently, it returns the facet fields for the collections group that don't include the **id**. We need to change the helper to return the correct **id** from collections.

From: 

```

def filter_collections(groups):
    all_collections = get_collections()
    
    return [value for value in groups if value['name'] in all_collections]

```

To:

```
def filter_collections(groups, complete=False):
    all_collections = get_collections()

    if complete:
        complete_collections = []
        context = { 'model': model, 'session': model.Session }
        for value in groups:
            if(value['name'] in all_collections):
                collection = logic.get_action('group_show')(context, {'id': value['name']})
                collection['count'] = value['count']
                complete_collections.append(collection)
        return complete_collections

    return [value for value in groups if value['name'] in all_collections]
```
This helper function is used only in the facet filtering search (```search.html``` file).

**Comment by nightsh** [comment]
First we need an analysis of how you're going to do it.
