### ISSUE TITLE
Clearing a filter in dataset search clears all filters

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-ed#260]
# Description

Having multiple filters selected, if the users press the “x” to clear one of them, it clears all of them instead.

Initial filters:

![image](https://user-images.githubusercontent.com/1579997/73762125-6f77ef00-4778-11ea-9793-da3154bfc37f.png)

Filters after clearing one of them:

![image](https://user-images.githubusercontent.com/1579997/73762141-73a40c80-4778-11ea-8aac-b80aa475af4a.png)

# Acceptance criteria:

- [ ] Clearing one of multiple filters in search page only clears the intended filter

# Tasks:

- [x] Understand the codebase, where this code resides and any dependencies
- [x] Write an analysis about how to approach
- [x] Define what is the best solution
- [x] Apply the solution
- [x] UAT locally
- [x] Submit PR to Victor to review
- [ ] Victor approves
- [ ] Victor to merge and deploy
- [ ] Higor UAT
- [ ] Esteban UAT

# Analysis:

Filters close buttons are redirecting the user to the datasets page ```\dataset```. The correct  URL to redirect is the one without the parameter related to the filter that the user is closing. 

For example:

URL for 2 filters applied, format and license: 
```/dataset?res_format=CSV&license_id=cc-zero```

When removing the format filter the user should be redirected to:
```dataset?license_id=cc-zero```
