### ISSUE TITLE
Default for docs should be public not private

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-ed#261]
## Description

Sometimes a non-logged in user would get a 404 when trying to view the docs tab of a data profile. We thought this was a bug but actually it wasn't - the default when adding docs is that they are private. 

Victor made the change so when this happens it is a 403 and not 404 (see link below and screen shot) We now need to change the default permissions when creating docs from private to public. 

https://us-ed-testing.ckan.io/dataset/docs/school-attendance-boundary-survey-2013-2014

![image](https://user-images.githubusercontent.com/1579997/73762336-bc5bc580-4778-11ea-829a-26eb8dcbdeda.png)

## Acceptance Criteria 

- [x] The default value for the visibility of the documents should be public.

## Tasks

- [x] Understand the codebase, where this code resides and any dependencies
- [x] Write an analysis about how to approach
- [x] Define what is the best solution
- [x] Apply the solution
- [x] UAT locally
- [x] Submit PR to Victor to review
- [x] Victor approves
- [x] Victor to merge and deploy
- [x] Higor UAT
- [x] Esteban UAT

## Analysis

The selected option in the combo box depends on the ```data.private``` field passed to the template (*documentation_basic_fields.html*) and it is rendered on creating new documentation or editing an existent one.

### Approach

Change the ```data.private``` value (from true to false) on the **New** action of the **Documentation Controller**.

**Comment by estebanruseler** [comment]
@higorspinto closing. Good job.
