### ISSUE TITLE
[bug] Collections / sources filters not being populated when not showing all groups in dataset search

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-ed#267]
# Description

On us-ed-testing.ckan.io - when entering the dataset search page, there are no collections / sources to choose from in the left hand sidebar filters.

However, clicking on "Show all" under Categories reveals all the possible options in Collections / Sources as well.

This is likely due to those filters being populated as subsets of the `groups` list in the search facets returned by `package_search` action.

We need to populate the list of collections / sources regardless of whether or not they might exist in the initial batch of `groups` returned by the search facets. This might involve fetching them separately and not collecting them from the facets anymore.

Moreover, if there are no collections / sources to be displayed, there should be a text stating it, as it is for the other search facets.

# Acceptance criteria:

- [ ] Visiting the dataset search page does not render empty lists of collections / sources
- [ ] List of collections / sources is unaffected by the show all / show less toggle in categories filter
- [ ] If there are no collections / sources to be shown, a text should indicate that
- [ ] With the collections / sources list populated, filtering should work as expected

# Tasks:

- [x] Analyze the cause of this bug
- [x] Analyze possible implementations
- [x] Implement a fix
- [x] UAT
- [x] Submit PR
- [ ] Merge / deploy

# Analysis

Collections and Sources are groups with different types. There is a limit for the number of groups that can be returned and shown at the screen. This limit is removed when the user clicks to show more.

## Approach 1

Read all groups with no limit and filter the collections and sources when rendering the filters. 

## Approach 2

Treat collections and sources as facets. It means include collection and sources as core facets. And refactor methods from helper and controller to include these new facets.

**Comment by nightsh** [comment]
@higorspinto how complicated you think it would be to try approach 2?

**Comment by higorspinto** [comment]
@nightsh The most complicated part is to reimplement ```search_facets``` from ckan.common. Not sure how much time I need. I agree with you, the best solution is described in approach 2.

**Comment by nightsh** [comment]
@higorspinto what if you statically collect all the collections that have datasets and their master collections and display them as facets? Would that be a good starting point?
