### ISSUE TITLE
Sidebar link sending to the wrong position

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-ed#269]
## Description

When a user clicks on a link on the side-bar (dataset page - description/docs) to go to another part of the same page, the target is shown a little bit below the correct position.

Dataset Information link:

![Screenshot from 2020-02-10 08-59-52](https://user-images.githubusercontent.com/20601698/74152279-b9cff480-4bec-11ea-9091-2e3ab2f6edb3.png)

When the user clicks on the link:

![Screenshot from 2020-02-10 09-01-12](https://user-images.githubusercontent.com/20601698/74152294-c0f70280-4bec-11ea-99db-5479050c785d.png)

Correct position:

![Screenshot from 2020-02-10 09-01-59](https://user-images.githubusercontent.com/20601698/74152441-0e736f80-4bed-11ea-92a8-477dfda21b7b.png)

## Acceptance Criteria

* [ ] The target is shown in the correct position

## Tasks

* [ ] Analyze code and why it's happening
* [ ] Propose solutions
* [ ] Pick up a solution
* [ ] Implement the solution
* [ ] UAT Locally
* [ ] Submit a PR
* [ ] Merge and deploy
* [ ] UAT on testing
