### ISSUE TITLE
Add Academic Year as a  time range filter

### ISSUE THREAD

**Issue by tanvirchahal** [CivicActions/ckanext-ed#273]
For time range in filters, have an academic year in the filter list

### Acceptance Criteria:

* [ ] Academic year can be selected from the filter dropdown
* [ ] Search Results are updated based on the academic year

### Tasks

* [ ] Update Filters list to add academic year option
* [ ] Update backend to support search with the academic year

**Comment by nightsh** [comment]
@tanvirchahal what is Academic Year? Is it the "Data Representation Period" from the form?

**Comment by tanvirchahal** [comment]
@nightsh for more reference, https://open-data-ed.atlassian.net/browse/OD-271
