### ISSUE TITLE
Categories list disappears when associating a collection to a dataset

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-ed#275]
## Description

When the user assigns a collection to a dataset in the dataset update page the list of categories related to this dataset disappears.

Dataset Categories page (before):

![Screenshot from 2020-02-13 10-01-57](https://user-images.githubusercontent.com/20601698/74437994-f51a2f80-4e47-11ea-966b-74b27992b2d7.png)

Updating the dataset (assigning a collection):

![Screenshot from 2020-02-13 10-03-30](https://user-images.githubusercontent.com/20601698/74438077-1f6bed00-4e48-11ea-9e30-264dd043bcaa.png)

Dataset Categories page (after):

![Screenshot from 2020-02-13 10-04-15](https://user-images.githubusercontent.com/20601698/74438157-49251400-4e48-11ea-94d5-b7de595f6943.png)

## Acceptance Criteria

* [ ] Categories list remains when assigning a collection to a dataset
* [ ] Association of collection and a dataset saved as well

## Tasks

* [ ]  Analyze the bug
* [ ] Propose solutions
* [ ] Pick up a solution
* [ ] Implement the solution
* [ ] UAT Locally
* [ ] Submit a PR
* [ ] Merge and deploy
* [ ] UAT on testing

## Questions 

* The collection list of a dataset should appear on the categories list?
