### ISSUE TITLE
Implement a show all / show less functionality for collections / sources filters in dataset search

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-ed#284]
**Context**

In the dataset search page we have a sidebar with filters. Most of them are Solr facets on their own, but Categories, Collections and Sources are all the same facet (`groups`), so a parallel filter implementation was made to make them appear as regular facets to the user.

**The Problem**

For the "regular" facets, CKAN generates a Show All / Show Less control that generates a query string parameter. For our separate implementation of Collections / Sources filters we don't have such a feature.

However, there will likely be many collections and sources in the site. The current implementation will attempt to display all of them in the search template with no option to collapse the list. Depending on the number of items, this could lead to either performance issues or crashes. This is bad.

**Tasks**

- [ ] investigate the functionality of Show All / Show Less for Categories facet
- [ ] investigate how to reuse bits of functionality without having to reinvent the wheel
- [ ] decide on a solution and implement
- [ ] UAT
- [ ] merge & deploy on the testing site

**Acceptance criteria**

- [ ] Collections and Sources filter have a Show All / Show less link below them
- [ ] The link looks and works the same as CKAN's default ones
