### ISSUE TITLE
Internal workflow improvements

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#38]
Improvements after PR review https://github.com/CivicActions/ckanext-ed/pull/37

## Tasks

* [x] https://github.com/CivicActions/ckanext-ed/pull/37#discussion_r243555675
* [x] https://github.com/CivicActions/ckanext-ed/pull/37#discussion_r243564578
* [x] https://github.com/CivicActions/ckanext-ed/pull/37#discussion_r243564578
* [x] https://github.com/CivicActions/ckanext-ed/pull/37#issuecomment-449379457

**Comment by amercader** [comment]
Done
