### ISSUE TITLE
[Epic] Create a section for documentation

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#55]
As a dept of ed. data creator, I want the ability to add documentation(s) to the dataset so that I can add well document data.

As a dept of ed. data creator, I want the ability to format the documentation so that reading experience is easy.

As a dept of ed. data creator, I want the ability to split the documentation into various sections, so I can rearrange them based on documentation’s type

## Acceptance Criteria

- [x] Users can upload documentation related to dataset when creating dataset (or update later)
- [x] Users can access documentation on a dedicated tab on dataset's page
- [ ] Documentation is well formatted (markdown)
- [x] Users can pin and re-arrange docs as desired

## Tasks

- [x] Mockups https://github.com/CivicActions/ckanext-ed/issues/56
- [x] Do the analysis and prepare spec for each sub item
- [x] Uploading documentation https://github.com/CivicActions/ckanext-ed/issues/59
- [x] View documentation https://github.com/CivicActions/ckanext-ed/issues/60
- [x] Pinn docs https://github.com/CivicActions/ckanext-ed/issues/57
- [x] Reorder docs https://github.com/CivicActions/ckanext-ed/issues/58
- [x] Deploy and present to project owner and sign off

**Comment by zelima** [comment]
FIXED
