### ISSUE TITLE
Mockups for documentation tab on dataset pages

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#56]
As a product owner I want to see the mockups for docs page, so that I know how it will look in advance and give my feedback on it

## Acceptance Criteria

* [x] Include url for the mockups here

Mockups: https://projects.invisionapp.com/share/XVQXIYWBKUD#/screens/351564173

## Tasks

* [x] Create mockups
* [x] Let team member review and get feadback
* [x] Let product owner review  and get feadback
* [x] Paste url

**Comment by zelima** [comment]
FIXED
