### ISSUE TITLE
Allow pinned documentation

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#57]
There is the ability to pin and unpin (and repin) documentation to the top of the documentation page. The user should be able to select docs to pin from the docs already added

As a Data steward, I was to highlight the most relevant documentation at the top of the documentation page so that I showcase this information and the documentation relevant to the latest data is easy to find.

## Acceptance Criteria

* [ ] Able to pin the doc

## Tasks

* [ ] Analysis 
* [ ] Field to save the state of the documentation (is it pinned or not) 12 hours
* [ ] Thought around the UI/UX of how to pin and unpin 4 hours
* [ ] Coding for pin/unpin 12 hours
* [ ] Front-end work so that it shows at the top 2 hours
* [ ] Test (6 hours)
* [ ] Deploy (1 hour)

## Low-level tasks

- [x] add a new field to resource schema `state` default `pinned` (or maybe field `pinned` with true/false?)
- [x] Controller for updating resource `state` field pinned/unpinned
- [x] Simple Button (for now) on resource edit page to call the ednpoint
- [ ] Update docs controller to keep pinned resource first on page - maybe use `package_resource_reorde`? https://docs.ckan.org/en/2.8/api/#ckan.logic.action.update.package_resource_reorder
- [ ] Think about reordering - how it should decline 

## Q/A

Q: How many docs can be pinned? 
A: Assume multiple 0 hours. - Multiple documents can be pinned, from different sections

Q: What happens if somebody rearranges pinned doc?

## Analysis

So here's how I imagine this:
- We have new field in `resource_schema` - `state=pinned/unpinned` - default to `unpinned`
- We have a controller or helper that updates the resource's `state`  field
- We have a button/icon that calls that helper function and updates resource properties
- We modify docs controller to keep pinned resource always first on the list
