### ISSUE TITLE
Ability to rearrange documentation sections

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#58]
The documentation added in various sections should be able to be rearranged from the administrator end.

As a dept of ed. employee, i want to rearrange the documentation sections, so that I can arrange the documentation in a meaningful order

As a dept of ed. employee, i want the ability to rearrange the documentation sections, so that I can group the relevant documentation in sections and make it easier for the users to understand.

## Acceptance Criteria

* [ ] Able to change the order of docs

## Tasks

* [ ] Use the ckan drag/drop functionality
* [ ] implement drag / drop on documentation sections
* [ ] improve visual design for the drag / drop and rearrange elements

**Comment by zelima** [comment]
@JGulic is there any relation with this extension to solve this https://extensions.ckan.org/extension/reorder/ ?
