### ISSUE TITLE
Display documentation on user end

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#60]
As a user, I want to see docs in a nice way (as in mockups) so that it's easy to use and read 

## Acceptance Criteria

* [ ] ~~Docs page looks like in mockups~~ - not now, this will be done later with general refactor
* [x] Regular resource and Documentations are on different tabs

## Tasks 

* [ ] Do analysis
* [ ] Compare using Markdown or check pages extension - CK Editor

## Low-level tasks

- [x] Update contoller for `dataset/{dataset-name}` to filter docs
- [x] Create controller for `dataset/docs/{dataset-name}` 
- [x] Create new tab on dataset page
- [x] create template for docs (or reuse one for regular resource) and upfate
- [x] Tests for contollers
- [x] do farther analysis for displaying docs page itself (for now it should be the same as the main, but only listing docs) 

## Analysis

Assuming that #59 is implemented, we will have the flag for each resources' type in `resource_type` field. This way we can filter regular resources and docs. 

- We will probably need to modify `dataset/tags-tets` controller to filter the ones with type `doc` 
- Also will need to create new controller for docs on `dataset/docs/{dataset-name}`

**Comment by zelima** [comment]
FIXED
