### ISSUE TITLE
[Discovery] What code base to create off - our codebase or data.gov.sg?

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#76]
As a project manager, I want analysis for https://data.gov.sg/ frontend code, so that I know if it's worth to re-use or continue our way.

## Acceptance Criteria

- [ ] We have pros and cons for both approaches 
- [x] We know which way to go

## Tasks

- [x] Where's data.gov.sg code?
- [x] Read the code and evaluate how complicated it is
- [x] How easy it is to refactor? How much work in hours?
- [x] Come up with the decision
- [x] Present to PM and let signoff

## Analysis 

TODO

**Comment by zelima** [comment]
FIXED data.gov.sg codebase is not public, so we will go our way
