### ISSUE TITLE
Disable approval process workflow

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#78]
As a PM I want to disable approval workflow as we don't need it anymore

## Acceptance Criteria

- [ ] No code related to workflow
- [ ] Tests are passing

## Tasks

- [x] Review the PR/commits introducing that feature
  - [x] sending emails https://github.com/CivicActions/ckanext-ed/commit/ef754a426444d7eccf3d3a3c874cece216a8ae92
  - [x] feadback popup https://github.com/CivicActions/ckanext-ed/commit/b56b716add33a590f150172c21695e79cbee5ee4
  - [x] dashboard for pending datasets https://github.com/CivicActions/ckanext-ed/commit/45deec6a0d67a065eea108e09387d0385f8424a1
  - [x] count pending datasets https://github.com/CivicActions/ckanext-ed/commit/c3997c46a7fbcc68328489c9e15b03b378671140
  - [x] activity workflow https://github.com/CivicActions/ckanext-ed/commit/a89075de5c4e161fe261c3f55ebd986bf15793a3
  - [x] button to make public on approval https://github.com/CivicActions/ckanext-ed/commit/4fc4d7772cd4d7f4d42365e02e92cecd8b207e91
- [x] List the files we need to modify
  - [x] Remove message for editors from package_create form
  - [x] remove requests dashboard (tab from dataset page)
  - [x] remove sending emails on approve/reject
  - [x] remove buttons 
  - [x] remove pensind datasets counter
- [x] Save changes on `feature/approval-workflow` branch
  - https://github.com/CivicActions/ckanext-ed/tree/feature/approval-workflow
- [x] Roll back the changes and tests
- [x] deploy

## Analysis

There are 2 ways to go here:

1. Remove everything related to approval workflow - backend and frontend, all API endpoints, email notifications, etc...
2. Remove only frontend related stuff and email notification. This way, users will know nothing about approval workflow, but we will keep endpoints and functions (doing nothing for now) and reuse later if needed - we might bring back modified approval workflow later.

**Comment by JGulic** [comment]
@zelima we are going with the option no.2 from the analysis. But before you start, create a branch that will have the current code that we have on master, in order to keep the functionality in case we need to go back to it again.

Another task that will come up from this one is to create a separate extension that will only contain the logic for the approval process. That way we can keep this separate, and install the extension if we need. (I am adding this task to the backlog)

**Comment by zelima** [comment]
FIXED
