### ISSUE TITLE
Bootstrap approval workflow

### ISSUE THREAD

**Issue by roll** [CivicActions/ckanext-ed#8]
# Overview

This issue is to implement the first simplified version of the approval workflow. It will be a good starting point to meet the high-level requirement on next steps. For some inspiration and reference see: https://github.com/okfn/ckanext-unhcr

# Tasks

- [ ] update `plugins.py`:
  - [ ] add `plugins.implements(plugins.IActions)`
  - [ ] register new action `dataset_create` pointing to  `actions.dataset_create`
- [ ] implement `actions.dataset_create`
  - [ ] sysadmin should create datasets passing all checks
  - [ ] users should create datasets with `not_approved` flag
  - [ ] all sysadmins should be notified if a new not approved dataset is added
  - [ ] implement sysadmins notifications based on `mailer.py`
- [ ] update `templates/dataset/read.html` to hide not approved datasets
  - [ ] see `templates/organization/read.html` at the `ckanext-unchr`
  - [ ] for users it should be hidden under `waiting approval`
  - [ ] for sysadmins there should be two buttons `approve` and `reject`
- [ ] implement logic for `approve` and `reject` buttons inside the `controller.py`
  - [ ] see `ckanext-unchr` as an example
  - [ ] to create new endpoints:
      - [ ] add `plugins.implements(plugins.IRoutes, inherit=True)` to the `plugin.py`
      - [ ] update `Plugin.before_map(self, _map):` based on `ckanext-unchr` example
  - [ ] on approval/rejection the dataset owner (user) should get a notification
  - [ ] implement user notification based on `mailer.py`
- [ ] add a note for users to the `templates/package/new_package_form.html` that this dataset will be in the approval loop after adding (e.g. `Request Dataset` instead of `Create Dataset` heading and a text note)
- [ ] test the feature manually (high-level) using a fake SMTP - https://github.com/CivicActions/ckanext-ed#testing-email-notifications
- [ ] add unit tests based on `ckanext-unchr` example

**Comment by amercader** [comment]
Closed in favour of #11
