### ISSUE TITLE
[Epic] Analytics

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#89]
As a sysadmin, I want to track the number of various events (downloads, visits, etc...) on the portal, so that I know  how the website is being used and make changes according to analytics if needed

## Tasks

- [ ] Discovery: Google Analytics for Event Tracking, Dataset Downloads, and Set up of a Dashboard
- [ ] Display counts of dataset downloads from GUI
- [ ] Set up Analytics to count the number of dataset downloads
