### ISSUE TITLE
Discovery: Google Analytics for Event Tracking, Dataset Downloads, and Set up of a Dashboard

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#90]
As a product owner, I want to monitor whether people are using the data in live websites (like does data.gov) so that I (and potentially website users) know how popular it is

As a product owner, I want to know the third party websites that use our API (like does data.gov), so that I can list them on the website and use that for marketing purposes

## Acceptance Criteria

- [ ] We have a detailed analysis of how to implement the features
- [ ] Estimate the effort and time for implementations 

## Tasks

- [ ] See data.gov portal and it's docs.
- [ ] Do analysis and estimate how the effort 
- [ ] Report

## Analysis

> more info on https://api.data.gov/about/. apparently agencies can sign up for api management services, which we did for the college scorecard. we get a little portal for analytics (who’s using the API, what columns of data they’re retrieving, etc). i’ll email them about it. note: the number of websites using this API is a stat from Google Fonts… not clear we could easily do that (e.g., monitor whether a live website is calling the API vs. development/experimentation)
