### ISSUE TITLE
Display counts of dataset downloads from GUI

### ISSUE THREAD

**Issue by zelima** [CivicActions/ckanext-ed#92]
As a sysadmin I want to display the count of dataset download so that end users and data stewards are able to see the popularity of a given public dataset (e.g., counts of dataset downloads)

## Acceptance Criteria

- [ ] Dataset page and info contains a number of downloads

## Tasks

- [ ] Implement the functionality 
- [ ] Descide on design (where it should be displayed)
- [ ] Tests
